const techStackTags = [
    { name: "JavaScript", description: "High-level, often just-in-time compiled language that conforms to the ECMAScript specification." },
    { name: "Python", description: "Interpreted, high-level, general-purpose programming language." },
    { name: "Java", description: "High-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible." },
    { name: "C#", description: "Modern, object-oriented, and type-safe programming language." },
    { name: "Ruby", description: "High-level, general-purpose programming language that is interpreted and uses garbage collection." },
    { name: "PHP", description: "General-purpose scripting language especially suited to web development." },
    { name: "C++", description: "General-purpose programming language created as an extension of the C programming language, or 'C with Classes'." },
    { name: "TypeScript", description: "Strict syntactical superset of JavaScript and adds optional static typing to the language." },
    { name: "Swift", description: "General-purpose, multi-paradigm, compiled programming language developed by Apple Inc. for iOS, macOS, watchOS, tvOS, and Linux." },
    { name: "Kotlin", description: "Cross-platform, statically typed, general-purpose programming language with type inference." },
    { name: "Go", description: "Statistically typed and compiled language that is syntactically similar to C but with memory safety, garbage collection, structural typing, and CSP-style concurrency." },
    { name: "Rust", description: "Multi-paradigm programming language focused on performance and safety, particularly safe concurrency." },
    { name: "Scala", description: "Strong static types, JVM and JavaScript runtimes that provide language interoperability." },
    { name: "Perl", description: "Family of two high-level, general-purpose, interpreted, dynamic programming languages, Perl 5 and Perl 6." },
    { name: "Haskell", description: "Standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing." },
    { name: "Lua", description: "Lightweight, high-level, multi-paradigm programming language designed primarily for embedded use in applications." },
    { name: "Clojure", description: "Modern, dynamic, and functional dialect of the Lisp programming language on the Java platform." },
    { name: "Elixir", description: "Functional, concurrent, general-purpose programming language that runs on the Erlang virtual machine (BEAM)." },
    { name: "Erlang", description: "General-purpose, concurrent, functional programming language, as well as a garbage-collected runtime system." },
    { name: "Dart", description: "Client-optimized language for fast apps on any platform." },
    { name: "Objective-C", description: "General-purpose, object-oriented programming language that adds Smalltalk-style messaging to the C programming language." },
    { name: "Groovy", description: "Object-oriented programming language for the Java platform." },
    { name: "MATLAB", description: "Multi-paradigm programming language and numeric computing environment developed by MathWorks." },
    { name: "R", description: "Programming language and free software environment for statistical computing and graphics supported by the R Foundation for Statistical Computing." },
    { name: "SQL", description: "Domain-specific language used in programming and designed for managing data held in a relational database management system." },
    { name: "NoSQL", description: "Mechanism for storage and retrieval of data that is modeled in means other than the tabular relations used in relational databases." },
    { name: "React", description: "JavaScript library for building user interfaces." },
    { name: "Angular", description: "Platform and framework for building single-page client applications using HTML and TypeScript." },
    { name: "Vue.js", description: "Progressive JavaScript framework for building UI on the web." },
    { name: "Svelte", description: "Radical new approach to building user interfaces." },
    { name: "Flutter", description: "UI software development kit created by Google for building natively compiled applications for mobile, web, and desktop from a single codebase." },
    { name: "Django", description: "High-level Python web framework that encourages rapid development and clean, pragmatic design." },
    { name: "Flask", description: "Micro web framework written in Python." },
    { name: "Spring Boot", description: "Project that makes it easy to create stand-alone, production-grade Spring based Applications that you can 'just run'." },
    { name: "ASP.NET", description: "Open-source server-side web application framework designed for web development to produce dynamic web pages." },
    { name: "Laravel", description: "PHP web application framework with expressive, elegant syntax." },
    { name: "Rails", description: "Server-side web application framework written in Ruby under the MIT License." },
    { name: "Express", description: "Back end web application framework for Node.js, designed for building web applications and APIs." },
    { name: "Node.js", description: "Back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser." },
    { name: "TensorFlow", description: "End-to-end open source platform for machine learning." },
    { name: "PyTorch", description: "Open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing." },
    { name: "Keras", description: "Deep learning API written in Python, running on top of the machine learning platform TensorFlow." },
    { name: "Pandas", description: "Software library written for the Python programming language for data manipulation and analysis." },
    { name: "NumPy", description: "Library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays." },
    { name: "Scikit-learn", description: "Machine learning library for the Python programming language." },
    { name: "GraphQL", description: "Open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data." },
    { name: "Redux", description: "Predictable state container for JavaScript apps." },
    { name: "MobX", description: "Simple, scalable state management." },
    { name: "Next.js", description: "React framework that enables functionality such as server-side rendering and generating static websites for React based web applications." },
    { name: "Gatsby", description: "React-based open source framework for creating websites and apps." },
    { name: "Electron", description: "Framework that lets you write cross-platform desktop applications using JavaScript, HTML and CSS." }
];

export default techStackTags;